site_name: orocommerce-cheatsheet
repo_url: https://github.com/kiboko-labs/orocommerce-cheatsheet
repo_name: Github
site_description: Documentation française pour OroCommerce
site_author: Kiboko
remote_branch: gh-pages
dev_addr: 'localhost:8010'
theme: readthedocs
nav:
    - Useful commands:
          - Oro 1.x: command/oro1.md
          - Oro 3.x: command/oro3.md
    - Backend tips:
          - Remove Price filter and sorter: backend/remove-price-filter.md
          - Comment créer un EventListener pour modifier une DataGrid:
                - Orm Result: backend/event-listener-datagrid-structure.md
                - Structure: backend/event-listener-datagrid-structure.md
          - Gérer dynamiquement des actions dans une datagrid: backend/dynamic-action-datagrid.md
          - Faire passer un paramètre à une datagrid: backend/pass-param-to-datagrid.md
          - Comment supprimer proprement une entité: backend/delete-entity.md
          - Faire des handlers / providers (update entity): backend/handler-provider-update.md
          - Champ select en config: backend/oro-config-select-type.md
    - Frontend tips:
          - BlockTypes examples: frontend/BlockTypes.md
          - List of Ui element present in OroUIBundle::macros.html.twig : frontend/ElementList.md
          - Find Twig Template block names: frontend/findblockname.md
          - Ajouter une Mass-Action sur la grille des produits: frontend/mass-actions.md
          - Create a frontend form for an entity: frontend/form.md
          - RGPD: frontend/consent-rgpd.md
    - Environment tips:
          - Installer Xdebug pour php 7.1 sur MacOS: environment/installer-xdebug-php71.md
          - Installer RabbitMQ avec Brew sur MacOS: environment/installer-rabbitmq-brew.md
          - Activer XDebug à la demande: environment/avoir-xdebug-a-la-demande.md
          - Utilisation de Supervisor: environment/supervisor.md
          - Utilisation de composer: environment/composer-tips.md
          - Insert product medias in the database: postgresql/insert-medias.md
          - Pour identifier les tables lourdes: postgresql/sql-tips.md
    - Migration tips: 
        - Introduction schema manipulation: migrations/introduction.md
        - Managing enums: migrations/enum.md
        - Extending an entity (Business Unit example): migrations/businessUnit.md
        - Managing the fields order on the form view: migrations/view.md
        - Configuring the platform via migrations: migrations/configuration.md
        - Delete completely an enum: migrations/delete-completely-an-enum.md
    - Docker tips:
        - Maninipuler des dumps.sql avec Docker: docker/dump-sql-docker.md
        - Utiliser le cache Docker: docker/use-cache.md
        - Nettoyer sa VM: docker/clean-vm.md
    - Test tips:
        - Intro: tests/intro.md
        - Behat: tests/behat.md
        - Javascript: tests/javascript.md
        - Functionnal: tests/functional.md

